#!/usr/bin/env bash
# HomeCare web container entrypoint.
#
# Renders includes/settings.php from environment variables, waits for
# MySQL to accept connections, applies schema + migrations on first
# boot (fresh database only), then hands off to the original Apache
# command.

set -euo pipefail

: "${HC_DB_HOST:=db}"
: "${HC_DB_PORT:=3306}"
: "${HC_DB_NAME:=homecare}"
: "${HC_DB_USER:=homecare}"
: "${HC_DB_PASSWORD:?HC_DB_PASSWORD is required}"
: "${HC_DB_TYPE:=mysqli}"
: "${HC_TIMEZONE:=America/New_York}"

SETTINGS_PATH=/var/www/html/includes/settings.php

# 1. Render settings.php from env. The legacy WebCalendar parser uses
#    a key:value comment block at the top; we mirror that shape so
#    nothing else has to change.
cat > "${SETTINGS_PATH}" <<EOF
<?php
/* Generated by docker-entrypoint.sh from environment variables.
   Re-rendered on every container start; do not edit by hand.
db_database: ${HC_DB_NAME}
db_debug: false
db_host: ${HC_DB_HOST}
db_login: ${HC_DB_USER}
db_password: ${HC_DB_PASSWORD}
db_persistent: false
db_type: ${HC_DB_TYPE}
readonly: false
use_http_auth: false
user_inc: user.php
mode: production
# end settings.php */
?>
EOF
chown www-data:www-data "${SETTINGS_PATH}"
chmod 0640 "${SETTINGS_PATH}"
echo "[entrypoint] Rendered ${SETTINGS_PATH}"

# 2. Wait for MySQL to (a) accept connections AND (b) finish creating
#    our user. MySQL 8 reports healthy on root-ping before the
#    secondary-user creation completes, so a simple ping isn't enough.
#    We probe with the actual app user; up to 120s.
echo "[entrypoint] Waiting for MySQL at ${HC_DB_HOST}:${HC_DB_PORT}..."
# `--ssl-mode=DISABLED` because MySQL 8 ships a self-signed cert by default
# and the cross-container hop fails the chain verify. PHP's mysqli does not
# negotiate TLS unless explicitly told to, so app traffic is unaffected by
# this client-side opt-out.
# Debian's `default-mysql-client` is MariaDB's, which uses `--skip-ssl`.
# (MySQL's own client wants `--ssl-mode=DISABLED`.) Either way the goal
# is the same: bypass MySQL 8's self-signed cert on the cross-container
# hop. PHP's mysqli does not negotiate TLS unless explicitly told to,
# so app traffic is unaffected.
MYSQL_CLIENT_OPTS=(--skip-ssl --connect-timeout=3)
for i in $(seq 1 120); do
    if mysql -h "${HC_DB_HOST}" -P "${HC_DB_PORT}" \
             -u "${HC_DB_USER}" -p"${HC_DB_PASSWORD}" \
             "${MYSQL_CLIENT_OPTS[@]}" \
             -e 'SELECT 1' >/dev/null 2>&1; then
        echo "[entrypoint] MySQL is up and our user can authenticate."
        break
    fi
    if [[ "$i" -eq 120 ]]; then
        echo "[entrypoint] FATAL: MySQL did not become reachable within 120s." >&2
        exit 1
    fi
    sleep 1
done

# 3. Initial schema + migrations on a fresh DB. We detect "fresh" by
#    looking for the hc_config table; if it doesn't exist, load
#    tables-mysql.sql and replay every numbered migration.
hc_config_exists=$(mysql -h "${HC_DB_HOST}" -P "${HC_DB_PORT}" \
        -u "${HC_DB_USER}" -p"${HC_DB_PASSWORD}" \
        "${MYSQL_CLIENT_OPTS[@]}" \
        -N -B -e "SELECT COUNT(*) FROM information_schema.tables \
                  WHERE table_schema='${HC_DB_NAME}' AND table_name='hc_config'")

if [[ "${hc_config_exists}" == "0" ]]; then
    echo "[entrypoint] Empty database detected — running migrations."
    # Load current schema (tables-mysql.sql already includes all migration changes)
    mysql -h "${HC_DB_HOST}" -P "${HC_DB_PORT}" \
          -u "${HC_DB_USER}" -p"${HC_DB_PASSWORD}" \
          "${MYSQL_CLIENT_OPTS[@]}" \
          "${HC_DB_NAME}" < /var/www/html/tables-mysql.sql

    # Create the migrations tracking table and mark all existing migrations
    # as applied — the base schema already includes their changes.
    mysql -h "${HC_DB_HOST}" -P "${HC_DB_PORT}" \
          -u "${HC_DB_USER}" -p"${HC_DB_PASSWORD}" \
          "${MYSQL_CLIENT_OPTS[@]}" \
          "${HC_DB_NAME}" <<'EOSQL'
CREATE TABLE IF NOT EXISTS hc_migrations (
    name VARCHAR(64) PRIMARY KEY,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
EOSQL

    for f in /var/www/html/migrations/*.sql; do
        mname=$(basename "$f")
        mysql -h "${HC_DB_HOST}" -P "${HC_DB_PORT}" \
              -u "${HC_DB_USER}" -p"${HC_DB_PASSWORD}" \
              "${MYSQL_CLIENT_OPTS[@]}" \
              "${HC_DB_NAME}" \
              -e "INSERT IGNORE INTO hc_migrations (name) VALUES ('${mname}')"
    done
    echo "[entrypoint] Base schema loaded; $(ls /var/www/html/migrations/*.sql | wc -l) migrations marked as applied."

    # Seed admin user (migration 004 contains the INSERT; the base schema
    # only has the table DDL). Safe to re-run — uses INSERT IGNORE or
    # IF NOT EXISTS.
    if [[ -f /var/www/html/migrations/004_seed_admin_user.sql ]]; then
        mysql -h "${HC_DB_HOST}" -P "${HC_DB_PORT}" \
              -u "${HC_DB_USER}" -p"${HC_DB_PASSWORD}" \
              "${MYSQL_CLIENT_OPTS[@]}" \
              "${HC_DB_NAME}" < /var/www/html/migrations/004_seed_admin_user.sql 2>/dev/null || true
        echo "[entrypoint] Admin user seeded."
    fi
    
    # Ensure version is set
    mysql -h "${HC_DB_HOST}" -P "${HC_DB_PORT}" \
          -u "${HC_DB_USER}" -p"${HC_DB_PASSWORD}" \
          "${MYSQL_CLIENT_OPTS[@]}" \
          "${HC_DB_NAME}" \
          -e "INSERT IGNORE INTO hc_config (setting, value) VALUES ('HOMECARE_PROGRAM_VERSION', 'v0.1.0')"

    echo "[entrypoint] Initial setup complete via migrations."
else
    echo "[entrypoint] Existing database — skipping init."
fi

# 4. Hand off.
exec "$@"
