<?php

declare(strict_types=1);

namespace HomeCare\Database;

/**
 * Minimal database contract used by the refactored repository and service layers.
 *
 * Keep this surface narrow on purpose: the legacy `dbi_*` helpers expose
 * dozens of knobs, but new code should only need parameterized reads
 * (`query`), parameterized writes (`execute`), and the last insert ID.
 */
interface DatabaseInterface
{
    /**
     * Run a parameterized SELECT and return every row as an associative array.
     *
     * Implementations MUST use bound parameters -- never interpolate $params
     * into $sql. An empty result set returns an empty array, not null.
     *
     * @param string            $sql    SQL with `?` placeholders.
     * @param list<scalar|null> $params Positional bind values.
     *
     * @return list<array<string,scalar|null>>
     *
     * @phpstan-impure The same SQL may return different results after any
     *                 intervening write; callers must not cache.
     */
    public function query(string $sql, array $params = []): array;

    /**
     * Run a parameterized INSERT/UPDATE/DELETE and return whether it succeeded.
     *
     * @param string            $sql    SQL with `?` placeholders.
     * @param list<scalar|null> $params Positional bind values.
     */
    public function execute(string $sql, array $params = []): bool;

    /**
     * Return the ID generated by the most recent INSERT.
     *
     * Behavior is undefined when no INSERT has been issued on this connection.
     */
    public function lastInsertId(): int;

    /**
     * Run $fn inside a transaction. Commit on normal return, roll back on
     * any Throwable (which is then re-thrown so callers see the failure).
     *
     * Nesting is not supported -- callers must not invoke another
     * `transactional()` from inside $fn.
     *
     * @template T
     *
     * @param callable():T $fn
     *
     * @return T
     */
    public function transactional(callable $fn): mixed;
}
